In [2]:
#Numpy to biblioteka, na której opiera się większość funkcjonalności Pythona w analizie danych.
#Jest ona bardzo szybka. Służy nam głównie do tworzenia tablic(ang. array) oraz macierzy.
#Numpy w znacznym stopniu ułatwia nam modyfikowanie ich.

In [3]:
#Pierwsze co robimy to importujemy numpy. 
#W dalszej części będziemy się odwoływać do niej jako 'np'.
import numpy as np

In [5]:
#Tworzymy tablicę za pomocą funkcji np.array()  
array = np.array( [0,1,2,3,4] )
array

array([0, 1, 2, 3, 4])

In [10]:
#Funkcja np.arange(start, stop, step_length) działa podobnie do range() 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Jak widzimy, w tablicy mamy co drugą wartość od 0 do 10.
#To dlatego, że długość kroku jest równa 2.
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
#Funkcja np.ones() tworzy nam tablicę wypełnioną jedynkami.
np.ones( 4 )

array([1., 1., 1., 1.])

In [18]:
#Żeby stworzyć tablicę np. 3 wiersze na 4 kolumny, 
#podajemy w argumencie funkcji (ilosc_wierszy,ilosc_kolumn)
np.ones( (3,4) ) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#Funkcja np.zeros() działa jak np.ones(), ale wypełnia tablicę zerami.
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
#Zwraca nam typ zmiennych w tablicy.
array.dtype

dtype('int32')

In [21]:
#Funkcja np.reshape(ilosc_wierszy,ilosc_kolumn), służy do zmieniania kształtu tablicy.
#Stwórzymy więc jednowymiarową tablicę z 30 wartościami.
array = np.arange(30)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
# array.shape zwraca nam kształt tablicy.
array.shape

(30,)

In [23]:
array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
#Pamiętajmy, że ilość wartości nie może się zmieniać poprzez zmienianie kształtu
#Dlatego nie możemy z tablicy 1 x 30 zrobić tablicy 5 x 7. Wyskoczy nam błąd.
array.reshape(5,7)

ValueError: cannot reshape array of size 30 into shape (5,7)

In [27]:
#Jeżeli nie chcemy, bądź nie możemy podawać liczby wierszy, 
#możemy wpisać liczbę -1. Oznacza to, że chcemy aby funkcja sama wyliczyła ilość wierszy.
#Jak widzimy w miejsce ilości wierszy podaliśmy -1, a w miejsce ilości kolumn 5.
#Powstała nam tablica 6 x 5.
array.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [28]:
#Tak samo możemy wstawić -1 w ilość kolumn.
array.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [30]:
#Funkcja np.linspace(start, stop, ilosc_kroków), zwraca w postaci tablicy
#równo rozmieszczone liczby w przedziale od start do stop. 
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [36]:
#Funkcja np.random.rand() zwraca losową liczbę od 0 do 1.
np.random.rand()

0.2213234024738966

In [38]:
#Funkcja np.random.randint(low, high, size) zwraca losową liczbę całkowitą od low do high.
np.random.randint(0,10) 

7

In [63]:
#Domyślnie size jest 1. 
#W tym przypadku funkcja zwraca nam tablicę 3 x 3.
array = np.random.randint(0,10, (3,3) )
array

array([[4, 5, 1],
       [0, 0, 3],
       [6, 8, 1]])

In [69]:
array = np.random.randint(0,23,7)
array

array([18, 10,  1, 11,  2, 12,  7])

In [70]:
#Funkcja max() zwraca największą wartość w tablicy.
array.max()

18

In [71]:
#Funkcja min() zwraca najmnieszą wartość w tablicy.
array.min()

1

In [72]:
#Funkcja argmax() zwraca pozycję największej wartości.
array.argmax()

0

In [73]:
#Funkcja argmin() zwraca pozycję najmniejszej wartości.
array.argmin()

2

In [25]:
#Zad 1
#Stwórz tablice z liczby od 0 do 50 podzielnych przez 5.

In [26]:
#Zad 2
#Zmień kształt tablicy do 2 x 5.

In [27]:
#Zad 3
#Stwórz tablicę z losowymi liczbami od 0 do 5. Kształt tablicy to 2 x 5. Nie stosuj funkcji reshape.

In [28]:
#Zad 4 
#Podziel tablice z pierwszego zadania przez tablice z zadania 3

In [59]:
#Zad 5
#Wyświetl najmniejszy i największy element w tablicy z zadania 4.